services:
  backend:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: portfolio_backend
    volumes:
      - .:/var/www/symfony
      - jwt_keys:/var/www/symfony/var/jwt
    env_file:
      - .env.local
    depends_on:
      - db
    networks:
      - symfony-network
    restart: unless-stopped

  db:
    image: postgres:17
    container_name: portfolio_db
    environment:
      POSTGRES_USER: portfolio
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: portfolio
    volumes:
      - portfolio_postgres:/var/lib/postgresql/data
    networks:
      - symfony-network
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: portfolio_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx/nginx.prod.conf:/etc/nginx/nginx.conf
      - ./public:/var/www/symfony/public
      # Décommenter après avoir généré les certificats SSL :
      # - /etc/letsencrypt:/etc/letsencrypt:ro
      # - ./certbot/www:/var/www/certbot:ro
    depends_on:
      - backend
    networks:
      - symfony-network
    restart: unless-stopped

  # ===================
  # MONITORING STACK
  # ===================

  prometheus:
    image: prom/prometheus:latest
    container_name: portfolio_prometheus
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=30d'
    networks:
      - symfony-network
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: portfolio_grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_AUTH_TWO_FACTOR_ENABLED=true
      - GF_AUTH_TWO_FACTOR_ORG_ENFORCED=true
      - GF_SERVER_ROOT_URL=https://grafana.${DOMAIN}
      - GF_SERVER_DOMAIN=grafana.${DOMAIN}
    volumes:
      - grafana_data:/var/lib/grafana
      - ./docker/grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - prometheus
    networks:
      - symfony-network
    restart: unless-stopped

  node-exporter:
    image: prom/node-exporter:latest
    container_name: portfolio_node_exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--path.rootfs=/rootfs'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    networks:
      - symfony-network
    restart: unless-stopped

  blackbox-exporter:
    image: prom/blackbox-exporter:latest
    container_name: portfolio_blackbox_exporter
    volumes:
      - ./docker/blackbox/blackbox.yml:/etc/blackbox_exporter/config.yml
    command:
      - '--config.file=/etc/blackbox_exporter/config.yml'
    networks:
      - symfony-network
    restart: unless-stopped

  nginx-exporter:
    image: nginx/nginx-prometheus-exporter:latest
    container_name: portfolio_nginx_exporter
    command:
      - '-nginx.scrape-uri=http://nginx:80/nginx_status'
    depends_on:
      - nginx
    networks:
      - symfony-network
    restart: unless-stopped

  postgres-exporter:
    image: prometheuscommunity/postgres-exporter:latest
    container_name: portfolio_postgres_exporter
    environment:
      DATA_SOURCE_NAME: "postgresql://portfolio:${DB_PASSWORD}@db:5432/portfolio?sslmode=disable"
    depends_on:
      - db
    networks:
      - symfony-network
    restart: unless-stopped

networks:
  symfony-network:

volumes:
  portfolio_postgres:
  jwt_keys:
  prometheus_data:
  grafana_data:
