services:
  backend:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: portfolio_backend
    volumes:
      - .:/var/www/symfony
    environment:
      DATABASE_URL: "postgresql://portfolio:portfolio@db:5432/portfolio?serverVersion=17&charset=utf8"
    depends_on:
      - db
    networks:
      - symfony-network

  db:
    image: postgres:17
    container_name: portfolio_db
    environment:
      POSTGRES_USER: portfolio
      POSTGRES_PASSWORD: portfolio
      POSTGRES_DB: portfolio
    volumes:
      - portfolio_postgres:/var/lib/postgresql/data
    networks:
      - symfony-network

  nginx:
    image: nginx:alpine
    container_name: portfolio_nginx
    ports:
      - 80:80
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./public:/var/www/symfony/public
    depends_on:
      - backend
    networks:
      - symfony-network

networks:
  symfony-network:

volumes:
  portfolio_postgres: